# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='岗位名称')),
                ('desc', models.TextField(default='', null=True, verbose_name='岗位描述')),
                ('skill', models.CharField(blank=True, help_text='一级瓦工', max_length=30, verbose_name='所需技能')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '岗位信息',
                'verbose_name_plural': '岗位信息',
            },
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='技能名称')),
                ('grade', models.IntegerField(default=0, verbose_name='技能等级')),
                ('desc', models.TextField(default='', verbose_name='岗位描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '技能信息',
                'verbose_name_plural': '技能信息',
            },
        ),
        migrations.CreateModel(
            name='TradeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='行业名称')),
                ('desc', models.TextField(default='', null=True, verbose_name='行业描述')),
                ('example', models.CharField(blank=True, max_length=200, verbose_name='著名公司')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '行业信息',
                'verbose_name_plural': '行业信息',
            },
        ),
    ]
