# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-16 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_auto_20180916_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trademodel',
            old_name='trade_name',
            new_name='name',
        ),
    ]
