# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-16 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cominfomodel',
            options={'verbose_name': '公司信息', 'verbose_name_plural': '公司信息'},
        ),
        migrations.AlterField(
            model_name='cominfomodel',
            name='trade',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='position.TradeModel', verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='comrecruitmodel',
            name='position',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='position.PositionModel', verbose_name='岗位'),
        ),
    ]
