# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180918_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='cominfomodel',
            name='img',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='com_img/%Y/%m', verbose_name='营业执照'),
        ),
    ]
