# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-17 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_cominfomodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cominfomodel',
            name='img',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='com_img/%Y/%m', verbose_name='证照图片'),
        ),
    ]
