# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-15 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewWorkerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(default='', max_length=30, verbose_name='工人姓名')),
                ('img', models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='头像')),
                ('gender', models.CharField(choices=[('female', '女'), ('male', '男')], default='female', max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('work_years', models.IntegerField(null=True, verbose_name='工龄')),
                ('now_salary', models.IntegerField(blank=True, default='', help_text='每月工资', verbose_name='目前薪资')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='个人简介')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '基本信息',
                'verbose_name_plural': '基本信息',
            },
        ),
        migrations.CreateModel(
            name='WorkerEduModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=30, verbose_name='学校名称')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('end_time', models.DateField(verbose_name='结束时间')),
                ('degree', models.CharField(help_text='如：初中', max_length=30, verbose_name='学位学历')),
                ('major', models.CharField(blank=True, max_length=30, null=True, verbose_name='专业')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmg.NewWorkerModel', verbose_name='工人')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
            },
        ),
        migrations.CreateModel(
            name='WorkerProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=30, verbose_name='项目名称')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('end_time', models.DateField(verbose_name='结束时间')),
                ('position', models.CharField(max_length=30, verbose_name='岗位')),
                ('skill', models.CharField(blank=True, help_text='一级瓦工', max_length=30, verbose_name='技能等级')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmg.NewWorkerModel', verbose_name='工人')),
            ],
            options={
                'verbose_name': '项目经验',
                'verbose_name_plural': '项目经验',
            },
        ),
        migrations.CreateModel(
            name='WorkerSkilltModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(default='', max_length=30, verbose_name='技能名称')),
                ('grade', models.IntegerField(default=1, verbose_name='技能等级')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmg.NewWorkerModel', verbose_name='工人')),
            ],
            options={
                'verbose_name': '工人技能',
                'verbose_name_plural': '工人技能',
            },
        ),
        migrations.CreateModel(
            name='WorkerWorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=30, verbose_name='公司名称')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('end_time', models.DateField(verbose_name='结束时间')),
                ('position', models.CharField(max_length=30, verbose_name='岗位')),
                ('skill', models.CharField(blank=True, help_text='一级瓦工', max_length=30, verbose_name='技能等级')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmg.NewWorkerModel', verbose_name='工人')),
            ],
            options={
                'verbose_name': '工作经验',
                'verbose_name_plural': '工作经验',
            },
        ),
    ]
