# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newworkermodel',
            name='peo_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证号'),
        ),
    ]
