# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-17 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position', '0002_auto_20180918_1413'),
        ('nmg', '0003_auto_20180928_1414'),
        ('company', '0005_auto_20181217_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyJudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.IntegerField(default=100000, verbose_name='评价编号')),
                ('worker_ability_score', models.CharField(choices=[('1分', '很差'), ('2分', '较差'), ('3分', '一般'), ('4分', '较好'), ('5分', '很好')], default='4', max_length=10, verbose_name='工作能力评价得分')),
                ('worker_ability_content', models.TextField(verbose_name='工作能力评价内容')),
                ('worker_ability_img', models.ImageField(blank=True, max_length=200, null=True, upload_to='CompanyJudge/%Y/%m', verbose_name='工作能力评价图片')),
                ('leader_content', models.TextField(verbose_name='直属领导的批语')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ComInfoModel', verbose_name='公司')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.PositionModel', verbose_name='岗位')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmg.WorkerWorkModel', verbose_name='工人')),
            ],
            options={
                'verbose_name': '公司评价',
                'verbose_name_plural': '公司评价',
            },
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_id', models.IntegerField(default=100000, verbose_name='报名编号')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ComInfoModel', verbose_name='公司')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.PositionModel', verbose_name='岗位')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmg.WorkerWorkModel', verbose_name='工人')),
            ],
            options={
                'verbose_name': '报名信息',
                'verbose_name_plural': '报名信息',
            },
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruit_id', models.IntegerField(default=100000, verbose_name='录取编号')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='录取时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ComInfoModel', verbose_name='公司')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.PositionModel', verbose_name='岗位')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmg.WorkerWorkModel', verbose_name='工人')),
            ],
            options={
                'verbose_name': '录取信息',
                'verbose_name_plural': '录取信息',
            },
        ),
        migrations.CreateModel(
            name='WorkerJudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.IntegerField(default=100000, verbose_name='评价编号')),
                ('work_envir_score', models.CharField(choices=[('1分', '很差'), ('2分', '较差'), ('3分', '一般'), ('4分', '较好'), ('5分', '很好')], default='4', max_length=10, verbose_name='工作环境评价得分')),
                ('work_envir_content', models.TextField(verbose_name='工作环境评价内容')),
                ('work_envir_img', models.ImageField(blank=True, max_length=200, null=True, upload_to='WorkerJudge/%Y/%m', verbose_name='工作环境评价图片')),
                ('work_salary_score', models.CharField(choices=[('1分', '很差'), ('2分', '较差'), ('3分', '一般'), ('4分', '较好'), ('5分', '很好')], default='4', max_length=10, verbose_name='工作薪资评价得分')),
                ('work_salary_content', models.TextField(verbose_name='工作薪资评价内容')),
                ('work_leader_score', models.CharField(choices=[('1分', '很差'), ('2分', '较差'), ('3分', '一般'), ('4分', '较好'), ('5分', '很好')], default='4', max_length=10, verbose_name='直属领导评价得分')),
                ('work_leader_content', models.TextField(verbose_name='直属领导评价内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ComInfoModel', verbose_name='公司')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.PositionModel', verbose_name='岗位')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmg.WorkerWorkModel', verbose_name='工人')),
            ],
            options={
                'verbose_name': '工人评价',
                'verbose_name_plural': '工人评价',
            },
        ),
    ]
