# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-29 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='推荐位名称')),
                ('img', models.ImageField(default='img/default1.jpg', max_length=200, upload_to='ban_img/%Y/%m', verbose_name='图片')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='链接')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '推荐位',
                'verbose_name_plural': '推荐位',
            },
        ),
    ]
