# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-10 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ynm', '0003_banner_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='发送邮箱')),
                ('send_type', models.CharField(choices=[('forget', '忘记密码')], default='forget', max_length=20, verbose_name='发送类型')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='desc',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
    ]
